name: CI and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Build Shadow JAR
        run: ./gradlew :plugin:dist:clean :plugin:dist:shadowJar --refresh-dependencies

      - name: Update Latest Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "plugin/dist/build/libs/Misty-*.jar"
          tag: "latest"
          name: "Latest Build"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true